-- luajit manage.lua moreinfo -fields weight:float height:float
-- luajit manage.lua detail -fields sex:bool age:int info::Moreinfo
-- luajit manage.lua user -fields username password age:int money:float detail::Detail
-- luajit manage.lua product -fields name price:float
-- luajit manage.lua record -fields buyer::User seller::User product::Product count:int time:datetime

local default = {
  output_path = 'apps',
  package_prefix = 'apps.',
}

local field_map = {
  string = "CharField", 
  int = "IntegerField", 
  text = "TextField", 
  float = "FloatField", 
  datetime = "DateTimeField", 
  date = "DateField", 
  time = "TimeField", 
  bool = 'BooleanField', 
} 

local function make_file(fn, content, context)
  for k, v in pairs(context or {}) do
    content = content:gsub('<%*'..k..'%*>', v)
  end
  local f, e = io.open(fn, "w+")
  if not f then
    return nil, e
  end
  local res, err = f:write(content)
  if not res then
    return nil, err
  end
  local res, err = f:close()
  if not res then
    return nil, err
  end
  return true
end

local make_dir
if package.config:sub(1,1) == '\\' then
  -- its windows
  function make_dir(s)
    local line = string.format('mkdir -p %s', s:gsub('/', '\\'))
    return os.execute(line)
  end
else
  function make_dir(s)
    local line = string.format('mkdir -p %s', s:gsub('\\', '/'))
    return os.execute(line)
  end
end

local head = [[-- Generated by file `manage.lua` at %s.  
]]
head = string.format(head, os.date())
local file_map = {
  urls = [[local ClassView = require"resty.mvc.view"
local views = require"<*package_prefix*><*name*>.views"
local models = require"<*package_prefix*><*name*>.models"
local forms = require"<*package_prefix*><*name*>.forms"

local <*model_name*> = models.<*model_name*>

return {
    {
      '^/<*name*>/create$',              
      ClassView.CreateView:as_view{
        model      = <*model_name*>,
        form_class = forms.<*model_name*>CreateForm,
      }
    },
  
    {
      '^/<*name*>/update/(?<id>\\d+?)$',              
      ClassView.UpdateView:as_view{
        model      = <*model_name*>,
        form_class = forms.<*model_name*>UpdateForm,
      }
    },

    {
      '^/<*name*>/list/(?<page>\\d+?)$',              
      ClassView.ListView:as_view{
        model = <*model_name*>,
      }
    },

    {
      '^/<*name*>/(?<id>\\d+?)$',              
      ClassView.DetailView:as_view{
        model = <*model_name*>,
      }
    },

    {
      '^/<*name*>/delete/(?<id>\\d+?)$',              
      ClassView.DeleteView:as_view{
        model = <*model_name*>,
      }
    },
}]], 
  views = [[local json = require "cjson.safe"
local Response = require"resty.mvc.response"
local ClassView = require"resty.mvc.view"
local query = require"resty.mvc.query".single
local models = require"<*package_prefix*><*name*>.models"
local forms = require"<*package_prefix*><*name*>.forms"

local <*model_name*> = models.<*model_name*>
local views = {}

-- function views.method(request)
--     return Response.Template("/")
-- end

return views
]], 
  models = [[local Model = require"resty.mvc.model"
local Field = require"resty.mvc.modelfield"
<*require_hooks*>

local <*model_name*> = Model:class{
    table_name = "<*name*>", 
    fields     = {
        <*fields*>
    }
}
-- function <*model_name*>.method(self)
--   -- define your model methods here
-- end

return {
  <*model_name*> = <*model_name*>, 
}]], 
  forms = [[local Form = require"resty.mvc.form"
local Widget = require"resty.mvc.widget"
local Field = require"resty.mvc.formfield"
local Validator = require"resty.mvc.validator"
local models = require"<*package_prefix*><*name*>.models"
<*require_hooks*>

local <*model_name*> = models.<*model_name*>

local <*model_name*>CreateForm = Form:class{
    model  = <*model_name*>, 
    fields = {
        <*fields*>
    }, 
}
-- function <*model_name*>CreateForm.instance(cls, attrs)
--     -- custom form initialization here
--     local self = Form.instance(cls, attrs)
--     return self
-- end

-- function <*model_name*>CreateForm.clean_fieldname(self, value)
--     -- define your form method here
--     return value
-- end


local <*model_name*>UpdateForm = Form:class{
    model  = <*model_name*>, 
    fields = {
        <*fields*>
    }, 
}
-- function <*model_name*>UpdateForm.instance(cls, attrs)
--     -- custom form initialization here
--     local self = Form.instance(cls, attrs)
--     return self
-- end
-- function <*model_name*>UpdateForm.clean_fieldname(self, value)
--     -- define your form method here
--     return value
-- end

return {
    <*model_name*>CreateForm = <*model_name*>CreateForm, 
    <*model_name*>UpdateForm = <*model_name*>UpdateForm, 
}]], 
}

local html_map = {
  create = [[
<form method="post">
  {*form:render()*}
  <button type="submit">create</button>
</form>]], 
  update = [[
<form method="post">
  {*form:render()*}
  <button type="submit">update</button>
</form>]], 
  detail = [[
<table class="table table-hover table-striped">
{% for k, v in pairs(object) do %}
  <tr>
    <th>{{k}}</th>
    <td>{{v}}</td>
  </tr>
{% end %}
</table>
<a href="/<*name*>/update/{{object.id}}" class="btn btn-default">edit</a>
]], 
  list = [[
<table class="table table-hover table-striped">
  {% if object_list[1] then %}
    <tr>
      {%for k, v in pairs(object_list[1]) do%}
        <th>{{k}}</th>
      {% end%}
      <th>Actions</th>
    </tr>
    {% for i, object in ipairs(object_list) do%}
    <tr>
      {%for k, v in pairs(object) do%}
      <td> {{v}} </td>
      {% end%}
      <td>
        <a href="/<*name*>/{{object.id}}" class="btn btn-default">detail</a>
        <a href="/<*name*>/update/{{object.id}}" class="btn btn-default">edit</a>
        <a href="/<*name*>/delete/{{object.id}}" class="btn btn-default">delete</a>
      </td>
    </tr>
    {% end%}
  {% else%}
    <p>No records</p>
  {% end%}
</table>]], 
}
local function capitalize(name)
  return name:sub(1, 1):upper()..name:sub(2)
end

local config = {}
local name = arg[1]
local model_name = capitalize(name)

local i = 2
if arg[2] == '-fields' then
  -- default values
  config.layout = 'base.html'
  config.block = 'main'
  i = i + 1
else
  local STATE = 'key'
  local key, value;
  while true do
    local v = arg[i]
    if STATE == 'key' then
      key = v:sub(2)
      if key == 'fields' then
        i = i+1
        break
      end
      STATE = 'value'
    else
      config[key] = v
      STATE = 'key'
    end
    i = i+1
  end
end
for k, v in ipairs(default) do
  if config[k] then
    default[k] = config[k]
  end
end

-- it does not matter the output_path exists
make_dir(default.output_path)

local dir = string.format('%s/%s',default.output_path, name)
local res, err = make_dir(dir)
assert(res, string.format('fail to create `%s`: %s.',dir, err))
print('create dir : '..dir)

-- MAKE TEMPLATE FILES
local template_dir = string.format('%s/html/%s', dir, name)
local res, err = make_dir(template_dir)
assert(res, string.format('fail to create `%s`: %s.',template_dir, err))
print('create dir : '..template_dir)

local layout = config.layout or config.l 
local block = config.block or config.b
for k, v in pairs(html_map) do
  if block then
    v = string.format('{-%s-}\n%s\n{-%s-}', block, v, block)
  end
  if layout then
    v = string.format('{%% layout = "%s" %%}\n\n', layout)..v
  end
  local fn = string.format('%s/%s.html',template_dir, k) 
  local res, err = make_file(fn, v, {name=name})
  assert(res, string.format('fail to create `%s`: %s.',fn, err))
  print('create file: '..fn)
end

-- MAKE LUA FILES
local fields = {}
local indent = '        ' --8 spaces
local require_hooks = {}
local foreignkeys = {} -- register foreignkey already defined
while true do
  local s = arg[i]
  if not s then
    break
  end
  local coln,colt 
  local foreignkey = false
  coln = string.match(s, [[^([%w_]+)$]])
  if coln then -- shortcuts for string type
    colt = 'string'
  else
    coln, colt  = string.match(s, [[^([%w_]+):([%w_]+)$]])
    if not coln then --check foreign key
      coln, colt  = string.match(s, [[^([%w_]+)::([%w_]+)$]])
      assert(coln, string.format(
        'fail to parse `%s`, valid form is `name:type` or `name::type`', s))
      foreignkey = true
    end
  end
  local field_string = ''
  if foreignkey then
    local model = colt
    local model_module = colt:lower()
    field_string = string.format('%s = Field.ForeignKey{%s}', coln, model)
    if not foreignkeys[model_module] then
      foreignkeys[model_module] = true
      require_hooks[#require_hooks+1] = string.format('local %s = require"%s%s.models".%s', 
        model, default.package_prefix, model_module, model)
    end
  else
    local field_template;
    if colt == 'string' or colt == 'text' then
      field_template = '%s = Field.%s{maxlen=50}'
    else
      field_template = '%s = Field.%s{}'
    end
    field_string = string.format(field_template, coln, field_map[colt] or 'CharField')
  end
  fields[#fields+1] = field_string
  i = i+1
end
local context = {name=name, model_name=model_name, fields=table.concat(fields, ',\n'..indent), 
  require_hooks = table.concat(require_hooks, '\n'), package_prefix=default.package_prefix,
}
for name, template in pairs(file_map) do
  -- for k,v in pairs(context) do
  --   template = template:gsub('<%*'..k..'%*>', v)
  -- end
  local fn = string.format('%s/%s.lua',dir, name)
  local res, err = make_file(fn, head..template, context)
  assert(res, string.format('fail to create `%s`: %s.',fn, err))
  print('create file: '..fn)  
end

