-- Generated by file `manage.lua` at Wed Oct 12 11:16:05 2016.  
local Form = require"resty.mvc.form"
local Widget = require"resty.mvc.widget"
local Field = require"resty.mvc.formfield"
local Validator = require"resty.mvc.validator"
local models = require"apps.user.models"
local Detail = require"apps.detail.models".Detail

local User = models.User

local UserCreateForm = Form:class{
    model  = User, 
    fields = {
        username = Field.CharField{maxlen=50},
        password = Field.CharField{maxlen=50},
        age = Field.IntegerField{},
        money = Field.FloatField{},
        detail = Field.ForeignKey{Detail}
    }, 
}
-- function UserCreateForm.clean_fieldname(self, value)
--     -- define your form method here
--     return value
-- end


local UserUpdateForm = Form:class{
    model  = User, 
    fields = {
        username = Field.CharField{maxlen=50},
        password = Field.CharField{maxlen=50},
        age = Field.IntegerField{},
        money = Field.FloatField{},
        detail = Field.ForeignKey{Detail}
    }, 
}
-- function UserUpdateForm.clean_fieldname(self, value)
--     -- define your form method here
--     return value
-- end

return {
    UserCreateForm = UserCreateForm, 
    UserUpdateForm = UserUpdateForm, 
}