-- Generated by file `manage.lua` at Fri Oct 14 13:25:36 2016.  
local Model = require"resty.mvc.model"
local Field = require"resty.mvc.modelfield"
local Detail = require"apps.detail.models".Detail

local User = Model:class{
    table_name = "user", 
    fields     = {
        username = Field.CharField{maxlen=50},
        password = Field.CharField{maxlen=50},
        age = Field.IntegerField{},
        money = Field.FloatField{},
        detail = Field.ForeignKey{Detail}
    }
}
-- define your model methods here
function User.render(self)
    return self.username
end

return {
  User = User, 
}