-- Generated by file `manage.lua` at Wed Oct 12 11:16:05 2016.  
local Model = require"resty.mvc.model"
local Field = require"resty.mvc.modelfield"
local Detail = require"apps.detail.models".Detail

local User = Model:class{
    table_name = "user", 
    fields     = {
        username = Field.CharField{maxlen=50},
        password = Field.CharField{maxlen=50},
        age = Field.IntegerField{},
        money = Field.FloatField{},
        detail = Field.ForeignKey{Detail}
    }
}
-- function User.method(self)
--   -- define your model methods here
-- end

return {
  User = User, 
}