-- Generated by file `manage.lua` at Fri Oct 14 13:25:36 2016.  
local json = require "cjson.safe"
local Response = require"resty.mvc.response"
local ClassView = require"resty.mvc.view"
local query = require"resty.mvc.query".single
local models = require"apps.user.models"
local forms = require"apps.user.forms"

local User = models.User

-- function user_home_view(request)
--     return Response.Template("/")
-- end

return {
    --  user_home_view = user_home_view,
}
