-- Generated by file `manage.lua` at Wed Oct 12 10:38:18 2016.  
local Form = require"resty.mvc.form"
local Widget = require"resty.mvc.widget"
local Field = require"resty.mvc.formfield"
local Validator = require"resty.mvc.validator"
local models = require"apps.product.models"


local Product = models.Product

local ProductCreateForm = Form:class{
    model  = Product, 
    fields = {
        name = Field.CharField{maxlen=50},
        price = Field.FloatField{}
    }, 
}
-- function ProductCreateForm.clean_fieldname(self, value)
--     -- define your form method here
--     return value
-- end


local ProductUpdateForm = Form:class{
    model  = Product, 
    fields = {
        name = Field.CharField{maxlen=50},
        price = Field.FloatField{}
    }, 
}
-- function ProductUpdateForm.clean_fieldname(self, value)
--     -- define your form method here
--     return value
-- end

return {
    ProductCreateForm = ProductCreateForm, 
    ProductUpdateForm = ProductUpdateForm, 
}