-- Generated by file `manage.lua` at Fri Oct 14 13:25:50 2016.  
local Form = require"resty.mvc.form"
local Widget = require"resty.mvc.widget"
local Field = require"resty.mvc.formfield"
local Validator = require"resty.mvc.validator"
local models = require"apps.product.models"


local Product = models.Product

local ProductCreateForm = Form:class{
    model  = Product, 
    fields = {
        name = Field.CharField{maxlen=50},
        price = Field.FloatField{}
    }, 
}
-- custom form initialization
-- function ProductCreateForm.instance(cls, attrs)
--     local self = Form.instance(cls, attrs)
--     return self
-- end

-- define your form clean method here
-- function ProductCreateForm.clean_fieldname(self, value)
--     return value
-- end


local ProductUpdateForm = Form:class{
    model  = Product, 
    fields = {
        name = Field.CharField{maxlen=50},
        price = Field.FloatField{}
    }, 
}

return {
    ProductCreateForm = ProductCreateForm, 
    ProductUpdateForm = ProductUpdateForm, 
}