-- Generated by file `manage.lua` at Fri Oct 14 13:25:50 2016.  
local Model = require"resty.mvc.model"
local Field = require"resty.mvc.modelfield"


local Product = Model:class{
    table_name = "product", 
    fields     = {
        name = Field.CharField{maxlen=50},
        price = Field.FloatField{}
    }
}
-- define your model methods here
function Product.render(self)
    return self.name
end

return {
  Product = Product, 
}