-- Generated by file `manage.lua` at Wed Oct 12 10:38:18 2016.  
local Model = require"resty.mvc.model"
local Field = require"resty.mvc.modelfield"


local Product = Model:class{
    table_name = "product", 
    fields     = {
        name = Field.CharField{maxlen=50},
        price = Field.FloatField{}
    }
}
-- function Product.method(self)
--   -- define your model methods here
-- end

return {
  Product = Product, 
}