-- Generated by file `manage.lua` at Wed Oct 12 10:38:18 2016.  
local json = require "cjson.safe"
local Response = require"resty.mvc.response"
local ClassView = require"resty.mvc.view"
local query = require"resty.mvc.query".single
local models = require"apps.product.models"
local forms = require"apps.product.forms"

local Product = models.Product
local views = {}

-- function views.method(request)
--     return Response.Template("/")
-- end

return views
