-- Generated by file `manage.lua` at Fri Oct 14 13:25:50 2016.  
local json = require "cjson.safe"
local Response = require"resty.mvc.response"
local ClassView = require"resty.mvc.view"
local query = require"resty.mvc.query".single
local models = require"apps.product.models"
local forms = require"apps.product.forms"

local Product = models.Product

-- function product_home_view(request)
--     return Response.Template("/")
-- end

return {
    --  product_home_view = product_home_view,
}
