-- Generated by file `manage.lua` at Fri Oct 14 13:25:58 2016.  
local Form = require"resty.mvc.form"
local Widget = require"resty.mvc.widget"
local Field = require"resty.mvc.formfield"
local Validator = require"resty.mvc.validator"
local models = require"apps.record.models"
local User = require"apps.user.models".User
local Product = require"apps.product.models".Product

local Record = models.Record

local RecordCreateForm = Form:class{
    model  = Record, 
    fields = {
        buyer = Field.ForeignKey{User},
        seller = Field.ForeignKey{User},
        product = Field.ForeignKey{Product},
        count = Field.IntegerField{},
        time = Field.DateTimeField{}
    }, 
}
-- custom form initialization
-- function RecordCreateForm.instance(cls, attrs)
--     local self = Form.instance(cls, attrs)
--     return self
-- end

-- define your form clean method here
-- function RecordCreateForm.clean_fieldname(self, value)
--     return value
-- end


local RecordUpdateForm = Form:class{
    model  = Record, 
    fields = {
        buyer = Field.ForeignKey{User},
        seller = Field.ForeignKey{User},
        product = Field.ForeignKey{Product},
        count = Field.IntegerField{},
        time = Field.DateTimeField{}
    }, 
}

return {
    RecordCreateForm = RecordCreateForm, 
    RecordUpdateForm = RecordUpdateForm, 
}