-- Generated by file `manage.lua` at Wed Oct 12 11:15:23 2016.  
local Form = require"resty.mvc.form"
local Widget = require"resty.mvc.widget"
local Field = require"resty.mvc.formfield"
local Validator = require"resty.mvc.validator"
local models = require"apps.record.models"
local User = require"apps.user.models".User
local Product = require"apps.product.models".Product

local Record = models.Record

local RecordCreateForm = Form:class{
    model  = Record, 
    fields = {
        buyer = Field.ForeignKey{User},
        seller = Field.ForeignKey{User},
        product = Field.ForeignKey{Product},
        count = Field.IntegerField{},
        time = Field.DateTimeField{}
    }, 
}
-- function RecordCreateForm.clean_fieldname(self, value)
--     -- define your form method here
--     return value
-- end


local RecordUpdateForm = Form:class{
    model  = Record, 
    fields = {
        buyer = Field.ForeignKey{User},
        seller = Field.ForeignKey{User},
        product = Field.ForeignKey{Product},
        count = Field.IntegerField{},
        time = Field.DateTimeField{}
    }, 
}
-- function RecordUpdateForm.clean_fieldname(self, value)
--     -- define your form method here
--     return value
-- end

return {
    RecordCreateForm = RecordCreateForm, 
    RecordUpdateForm = RecordUpdateForm, 
}