-- Generated by file `manage.lua` at Fri Oct 14 13:25:58 2016.  
local Model = require"resty.mvc.model"
local Field = require"resty.mvc.modelfield"
local User = require"apps.user.models".User
local Product = require"apps.product.models".Product

local Record = Model:class{
    table_name = "record", 
    fields     = {
        buyer = Field.ForeignKey{User},
        seller = Field.ForeignKey{User},
        product = Field.ForeignKey{Product},
        count = Field.IntegerField{},
        time = Field.DateTimeField{}
    }
}
-- define your model methods here
-- function Record.render(self)
--     return 
-- end

return {
  Record = Record, 
}