-- Generated by file `manage.lua` at Wed Oct 12 11:15:23 2016.  
local Model = require"resty.mvc.model"
local Field = require"resty.mvc.modelfield"
local User = require"apps.user.models".User
local Product = require"apps.product.models".Product

local Record = Model:class{
    table_name = "record", 
    fields     = {
        buyer = Field.ForeignKey{User},
        seller = Field.ForeignKey{User},
        product = Field.ForeignKey{Product},
        count = Field.IntegerField{},
        time = Field.DateTimeField{}
    }
}
-- function Record.method(self)
--   -- define your model methods here
-- end

return {
  Record = Record, 
}