-- Generated by file `manage.lua` at Wed Oct 12 11:15:23 2016.  
local ClassView = require"resty.mvc.view"
local views = require"apps.record.views"
local models = require"apps.record.models"
local forms = require"apps.record.forms"

local Record = models.Record

return {
    {
      '^/record/create$',              
      ClassView.CreateView:as_view{
        model      = Record,
        form_class = forms.RecordCreateForm,
      }
    },
  
    {
      '^/record/update/(?<id>\\d+?)$',              
      ClassView.UpdateView:as_view{
        model      = Record,
        form_class = forms.RecordUpdateForm,
      }
    },

    {
      '^/record/list/(?<page>\\d+?)$',              
      ClassView.ListView:as_view{
        model = Record,
      }
    },

    {
      '^/record/(?<id>\\d+?)$',              
      ClassView.DetailView:as_view{
        model = Record,
      }
    },

    {
      '^/record/delete/(?<id>\\d+?)$',              
      ClassView.DeleteView:as_view{
        model = Record,
      }
    },
}