-- Generated by file `manage.lua` at Fri Oct 14 13:25:58 2016.  
local json = require "cjson.safe"
local Response = require"resty.mvc.response"
local ClassView = require"resty.mvc.view"
local query = require"resty.mvc.query".single
local models = require"apps.record.models"
local forms = require"apps.record.forms"

local Record = models.Record

-- function record_home_view(request)
--     return Response.Template("/")
-- end

return {
    --  record_home_view = record_home_view,
}
