-- Generated by file `manage.lua` at 2016-9-21 0:24:17. Inspired by Django. 
local Model = require"resty.mvc.model"
local Field = require"resty.mvc.model_field"


local User = Model:class{table_name = "user", 
    fields = {
        username = Field.CharField{maxlen=50},
        password = Field.CharField{maxlen=50},
        age = Field.IntegerField{},
        class = Field.CharField{maxlen=50, choices={{'ty', '共青团员'}, {'dy', '中共党员'}}, }
    }
}
-- function User.foobar(self)
--   -- define your model methods here like this
-- end

return {
  User = User, 
}