-- Generated by file `manage.lua` at 10/02/16 17:56:19.  
local Model = require"resty.mvc.model"
local Field = require"resty.mvc.modelfield"
local User = require"app.user.models".User
local Product = require"app.product.models".Product

local Record = Model:class{table_name = "record", 
    fields = {
        buyer = Field.ForeignKey{User},
        seller = Field.ForeignKey{User},
        product = Field.ForeignKey{Product},
        count = Field.IntegerField{},
        time = Field.DateTimeField{}
    }
}
-- function Record.method(self)
--   -- define your model methods here like this
-- end

return {
  Record = Record, 
}