-- Generated by file `manage.lua` at 10/02/16 17:56:19.  
local json = require "cjson.safe"
local Response = require"resty.mvc.response"
local ClassView = require"resty.mvc.view"
local query = require"resty.mvc.query".single
local models = require"app.record.models"
local forms = require"app.record.forms"

local Record = models.Record
local views = {}

-- function views.method(request)
--     return Response.Template("/")
-- end

return views
