-- Generated by file `manage.lua` at Mon Oct 17 05:09:55 2016.  
local Model = require"resty.mvc.model"
local Field = require"resty.mvc.modelfield"


local Product = Model:class{
    meta   = {

    },
    fields = {
        name = Field.CharField{maxlen=50},
        price = Field.FloatField{}
    }
}
-- define your model methods here
-- function Product.render(self)
--     return 
-- end

return {
  Product = Product, 
}