-- Generated by file `manage.lua` at Mon Oct 17 05:09:55 2016.  
local ClassView = require"resty.mvc.view"
local views = require"apps.company.views"
local models = require"apps.company.models"
local forms = require"apps.company.forms"

local Product = models.Product

return {
    {
      '/company/product/create',              
      ClassView.CreateView:as_view{
        model      = Product,
        form_class = forms.ProductCreateForm,
      }
    },
  
    {
      '/company/product/update',              
      ClassView.UpdateView:as_view{
        model      = Product,
        form_class = forms.ProductUpdateForm,
      }
    },

    {
      '/company/product/list',              
      ClassView.ListView:as_view{
        model = Product,
      }
    },

    {
      '/company/product',              
      ClassView.DetailView:as_view{
        model = Product,
      }
    },

    {
      '/company/product/delete',              
      ClassView.DeleteView:as_view{
        model = Product,
      }
    },
}