-- Generated by file `manage.lua` at Mon Oct 17 05:09:55 2016.  
local json = require "cjson.safe"
local Response = require"resty.mvc.response"
local ClassView = require"resty.mvc.view"
local query = require"resty.mvc.query".single
local models = require"apps.company.models"
local forms = require"apps.company.forms"

local Product = models.Product

-- function product_home(request)
--     return Response.Template(request, "product/home.html")
-- end

return {
    --  product_home = product_home,
}
