-- Generated by file `manage.lua` at 10/02/16 17:56:11.  
local Model = require"resty.mvc.model"
local Field = require"resty.mvc.modelfield"


local Product = Model:class{table_name = "product", 
    fields = {
        name = Field.CharField{maxlen=50},
        price = Field.FloatField{}
    }
}
-- function Product.method(self)
--   -- define your model methods here like this
-- end

return {
  Product = Product, 
}