-- Generated by file `manage.lua` at 09/30/16 16:43:16.  
local Form = require"resty.mvc.form"
local Widget = require"resty.mvc.widget"
local Field = require"resty.mvc.formfield"
local Validator = require"resty.mvc.validator"
local models = require"app.pet.models"
local User = require"app.user.models".User

local Pet = models.Pet

local PetCreateForm = Form:class{model = Pet, 
    fields = {
        --mom = Field.ForeignKey{User},
        --dad = Field.ForeignKey{User},
        name = Field.CharField{maxlen=50},
        age = Field.IntegerField{}
    }, 
}
-- function PetCreateForm.clean_foobar(self, value)
--     -- define your form method here like this
--     return value
-- end


local PetUpdateForm = Form:class{model = Pet, 
    fields = {
        --mom = Field.ForeignKey{User},
        --dad = Field.ForeignKey{User},
        name = Field.CharField{maxlen=50},
        age = Field.IntegerField{}
    }, 
}
-- function PetUpdateForm.clean_foobar(self, value)
--     -- define your form method here like this
--     return value
-- end

return {
    PetCreateForm = PetCreateForm, 
    PetUpdateForm = PetUpdateForm, 
}