-- Generated by file `manage.lua` at 2016-9-22 15:23:7. Inspired by Django. 
local Form = require"resty.mvc.form"
local widget = require"resty.mvc.widget"
local Field = require"resty.mvc.form_field"
local validator = require"resty.mvc.validator"
local models = require"app.pet.models"
local User = require"app.user.models".User

local Pet = models.Pet

local PetCreateForm = Form:class{model = Pet, 
    fields = {
        user = Field.ForeignKey{User},
        name = Field.CharField{maxlen=50}
    }, 
}
-- function PetCreateForm.clean_foobar(self, value)
--     -- define your form method here like this
--     return value
-- end


local PetUpdateForm = Form:class{model = Pet, 
    fields = {
        user = Field.ForeignKey{User},
        name = Field.CharField{maxlen=50}
    }, 
}
-- function PetUpdateForm.clean_foobar(self, value)
--     -- define your form method here like this
--     return value
-- end

return {
    PetCreateForm = PetCreateForm, 
    PetUpdateForm = PetUpdateForm, 
}