-- Generated by file `manage.lua` at 2016-9-22 15:23:7. Inspired by Django. 
local Model = require"resty.mvc.model"
local Field = require"resty.mvc.model_field"
local User = require"app.user.models".User

local Pet = Model:class{table_name = "pet", 
    fields = {
        user = Field.ForeignKey{User},
        name = Field.CharField{maxlen=50}
    }
}
-- function Pet.foobar(self)
--   -- define your model methods here like this
-- end

return {
  Pet = Pet, 
}