-- Generated by file `manage.lua` at 09/30/16 16:43:16.  
local Model = require"resty.mvc.model"
local Field = require"resty.mvc.modelfield"
local User = require"app.user.models".User

local Pet = Model:class{table_name = "pet", 
    fields = {
        mom = Field.ForeignKey{User},
        dad = Field.ForeignKey{User},
        name = Field.CharField{maxlen=50},
        age = Field.IntegerField{}
    }
}
-- function Pet.foobar(self)
--   -- define your model methods here like this
-- end

return {
  Pet = Pet, 
}