-- Generated by file `manage.lua` at 09/30/16 16:43:16.  
local ClassView = require"resty.mvc.view"
local views = require"app.pet.views"
local models = require"app.pet.models"
local forms = require"app.pet.forms"

local Pet = models.Pet

return {
  {'^/pet/create$',              ClassView.CreateView:as_view{model=Pet,form_class=forms.PetCreateForm}}, 
  {'^/pet/update/(?<id>\\d+?)$', ClassView.UpdateView:as_view{model=Pet,form_class=forms.PetUpdateForm}}, 
  {'^/pet/list/(?<page>\\d+?)$', ClassView.ListView:as_view{model=Pet}}, 
  {'^/pet/(?<id>\\d+?)$',        ClassView.DetailView:as_view{model=Pet}}, 
  {'^/pet/delete/(?<id>\\d+?)$', ClassView.DeleteView:as_view{model=Pet}}, 
}