-- Generated by file `manage.lua` at 09/30/16 16:43:16.  
local json = require "cjson.safe"
local Response = require"resty.mvc.response"
local ClassView = require"resty.mvc.view"
local query = require"resty.mvc.query".single
local models = require"app.pet.models"
local forms = require"app.pet.forms"

local Pet = models.Pet
local views = {}

-- function views.foobar(request)
--     return Response.Template("/")
-- end

return views
