-- Generated by file `manage.lua` at 2016-9-22 15:23:7. Inspired by Django. 
local json = require "cjson.safe"
local query = require"resty.mvc.query".single
local response = require"resty.mvc.response"
local ClassView = require"resty.mvc.view"
local models = require"app.pet.models"
local forms = require"app.pet.forms"

local Pet = models.Pet
local views = {}

-- function views.foobar(request)
--     return response.Template("/")
-- end

return views
