-- Generated by file `manage.lua` at Sun Oct 16 13:07:13 2016.  
local Form = require"resty.mvc.form"
local Widget = require"resty.mvc.widget"
local Field = require"resty.mvc.formfield"
local Validator = require"resty.mvc.validator"
local models = require"apps.accounts.models"


local User = models.User

local UserCreateForm = Form:class{
    model  = User, 
    fields = {
        username = Field.CharField{maxlen=50},
        password = Field.CharField{maxlen=50}
    }, 
}
-- custom form initialization
-- function UserCreateForm.instance(cls, attrs)
--     local self = Form.instance(cls, attrs)
--     return self
-- end

-- define your form clean method here
-- function UserCreateForm.clean_fieldname(self, value)
--     return value
-- end


local UserUpdateForm = Form:class{
    model  = User, 
    fields = {
        username = Field.CharField{maxlen=50},
        password = Field.CharField{maxlen=50}
    }, 
}

return {
    UserCreateForm = UserCreateForm, 
    UserUpdateForm = UserUpdateForm, 
}