-- Generated by file `manage.lua` at Sun Oct 16 13:07:13 2016.  
local Model = require"resty.mvc.model"
local Field = require"resty.mvc.modelfield"


local User = Model:class{
    fields     = {
        username = Field.CharField{maxlen=50},
        password = Field.CharField{maxlen=50}
    }
}

local Profile = Model:class{
    fields     = {
        user = Field.ForeignKey{User},
        sex = Field.IntegerField{}
    }
}

-- define your model methods here
-- function User.render(self)
--     return 
-- end

return {
  User = User, 
  Profile = Profile,
}