-- Generated by file `manage.lua` at Sun Oct 16 13:07:13 2016.  
local ClassView = require"resty.mvc.view"
local views = require"apps.accounts.views"
local models = require"apps.accounts.models"
local forms = require"apps.accounts.forms"

local User = models.User

return {
    {
      '/accounts/user/create$',              
      ClassView.CreateView:as_view{
        model      = User,
        form_class = forms.UserCreateForm,
      }
    },
  
    {
      '^/accounts/user/update/(?<id>\\d+?)$',              
      ClassView.UpdateView:as_view{
        model      = User,
        form_class = forms.UserUpdateForm,
      }
    },

    {
      '^/accounts/user/list/(?<page>\\d+?)$',              
      ClassView.ListView:as_view{
        model = User,
      }
    },

    {
      '^/accounts/user/(?<id>\\d+?)$',              
      ClassView.DetailView:as_view{
        model = User,
      }
    },

    {
      '^/accounts/user/delete/(?<id>\\d+?)$',              
      ClassView.DeleteView:as_view{
        model = User,
      }
    },
}