-- Generated by file `manage.lua` at Sun Oct 16 13:07:13 2016.  
local json = require "cjson.safe"
local Response = require"resty.mvc.response"
local ClassView = require"resty.mvc.view"
local query = require"resty.mvc.query".single
local models = require"apps.accounts.models"
local forms = require"apps.accounts.forms"

local User = models.User

-- function user_home(request)
--     return Response.Template(request, "user/home.html")
-- end

return {
    --  user_home = user_home,
}
