-- Generated by file `manage.lua` at 09/23/16 22:41:24.  
local Form = require"resty.mvc.form"
local Widget = require"resty.mvc.widget"
local Field = require"resty.mvc.formfield"
local Validator = require"resty.mvc.validator"
local models = require"app.user.models"


local User = models.User

local UserCreateForm = Form:class{model = User, 
    fields = {
        name = Field.CharField{maxlen=10},
        class = Field.ChoiceField{maxlen=5, choices={{'1', '三年一班'}, {'2', '三年二班'}}},
        age = Field.IntegerField{min=6, max=100},
        score = Field.FloatField{min=0, max=150},
        passed = Field.BooleanField{},
    }, 
}
-- function UserCreateForm.clean_foobar(self, value)
--     -- define your form method here like this
--     return value
-- end

local mfs = {}
for k,v in pairs(User.fields) do
    mfs[k] = v:formfield()
end
local UserUpdateForm = Form:class{model = User, 
    fields = mfs, 
    -- fields = {
    --     name = Field.CharField{maxlen=50},
    --     class = Field.CharField{maxlen=50},
    --     age = Field.IntegerField{},
    --     score = Field.FloatField{},
    --     passed = Field.BooleanField{},
    -- }, 
}
-- function UserUpdateForm.clean_foobar(self, value)
--     -- define your form method here like this
--     return value
-- end

return {
    UserCreateForm = UserCreateForm, 
    UserUpdateForm = UserUpdateForm, 
}