-- Generated by file `manage.lua` at 2016-9-9 0:44:1. Inspired by Django. 
-- Modify it as you wish.
local Form = require"resty.mvc.form"
local Field = require"resty.mvc.form_field"
local validator = require"resty.mvc.validator"
local models = require"app.user.models"
local Widget = require"resty.mvc.widget"


local User = models.User

local UserCreateForm = Form:class{model = User, 
    fields = {
        username = Field.CharField{maxlen=1},
        password = Field.CharField{maxlen=50},
    }, 
}
-- function UserCreateForm.clean_foobar(self, value)
--     -- define your form method here like this
--     return value
-- end


local UserUpdateForm = Form:class{model = User, 
    fields = {
        username = Field.ChoiceField{ widget=Widget.RadioSelect, 
            choices={{'a', '啊'}, {'b', '比'}}, help_text='名字, 最多1个字'},
        password = Field.CharField{widget=Widget.TextInput, maxlen=50},
    }, 
}
-- function UserUpdateForm.clean_foobar(self, value)
--     -- define your form method here like this
--     return value
-- end

return {
    UserCreateForm = UserCreateForm, 
    UserUpdateForm = UserUpdateForm, 
}