-- Generated by file `manage.lua` at 09/30/16 16:47:14.  
local Form = require"resty.mvc.form"
local Widget = require"resty.mvc.widget"
local Field = require"resty.mvc.formfield"
local Validator = require"resty.mvc.validator"
local models = require"app.user.models"


local User = models.User

local UserCreateForm = Form:class{model = User, 
    fields = {
        name = Field.CharField{maxlen=50},
        age = Field.IntegerField{}
    }, 
}
-- function UserCreateForm.clean_foobar(self, value)
--     -- define your form method here like this
--     return value
-- end


local UserUpdateForm = Form:class{model = User, 
    fields = {
        name = Field.CharField{maxlen=50},
        age = Field.IntegerField{}
    }, 
}
-- function UserUpdateForm.clean_foobar(self, value)
--     -- define your form method here like this
--     return value
-- end

return {
    UserCreateForm = UserCreateForm, 
    UserUpdateForm = UserUpdateForm, 
}