-- Generated by file `manage.lua` at 09/30/16 16:47:14.  
local Model = require"resty.mvc.model"
local Field = require"resty.mvc.modelfield"


local User = Model:class{table_name = "user", 
    fields = {
        name = Field.CharField{maxlen=50},
        age = Field.IntegerField{}
    }
}
-- function User.foobar(self)
--   -- define your model methods here like this
-- end

return {
  User = User, 
}