-- Generated by file `manage.lua` at 10/02/16 17:55:48.  
local Model = require"resty.mvc.model"
local Field = require"resty.mvc.modelfield"

local Detail = Model:class{table_name = "detail", 
    fields = {
        sex = Field.CharField{maxlen=1},
        age = Field.IntegerField{},
        money = Field.FloatField{}, 
    }
}

local User = Model:class{table_name = "user", 
    fields = {
        name = Field.CharField{maxlen=50},
        detail = Field.ForeignKey{Detail}
    }
}
-- function User.method(self)
--   -- define your model methods here like this
-- end

return {
  User = User, 
  Detail = Detail, 
}