-- Generated by file `manage.lua` at 09/23/16 22:41:24.  
local Model = require"resty.mvc.model"
local Field = require"resty.mvc.modelfield"


local User = Model:class{table_name = "user", 
    fields = {
        name = Field.CharField{maxlen=10},
        class = Field.IntegerField{choices={{1, '三年一班'}, {2, '三年二班'}}},
        age = Field.IntegerField{min=6, max=100},
        score = Field.FloatField{min=0, max=150},
        passed = Field.BooleanField{},
        create_time = Field.DateTimeField{auto_now_add=true},
        update_time = Field.DateTimeField{auto_now=true}
    }
}
-- function User.foobar(self)
--   -- define your model methods here like this
-- end

return {
  User = User, 
}