-- Generated by file `manage.lua` at 2016-9-23 0:33:28.  
local json = require "cjson.safe"
local query = require"resty.mvc.query".single
local response = require"resty.mvc.response"
local ClassView = require"resty.mvc.view"
local models = require"app.user.models"
local forms = require"app.user.forms"

local User = models.User
local views = {}

-- function views.foobar(request)
--     return response.Template("/")
-- end

return views
