-- Generated by file `manage.lua` at 2016-9-9 0:44:1. Inspired by Django. 
-- Modify it as you wish.
local json = require "cjson.safe"
local query = require"resty.mvc.query".single
local response = require"resty.mvc.response"
local ClassView = require"resty.mvc.view"
local models = require"app.user.models"
local forms = require"app.user.forms"

local User = models.User
local views = {}

-- function views.foobar(request, kwargs)
--     return response.Template("/")
-- end

return views
