-- Generated by file `manage.lua` at 2016-9-10 0:7:16. Inspired by Django. 
-- Modify it as you wish.
local Form = require"resty.mvc.form"
local Field = require"resty.mvc.field"
local validator = require"resty.mvc.validator"
local models = require"app.thread.models"
local User = require"app.user.models".User

local Thread = models.Thread

local ThreadCreateForm = Form:class{model = Thread, 
    fields = {
        title = Field.CharField{maxlen=50},
        content = Field.TextField{maxlen=500}
    }, 
}
-- function ThreadCreateForm.clean_foobar(self, value)
--     -- define your form method here like this
--     return value
-- end


local ThreadUpdateForm = Form:class{model = Thread, 
    fields = {
        title = Field.CharField{maxlen=50},
        content = Field.TextField{maxlen=500}
    }, 
}
-- function ThreadUpdateForm.clean_foobar(self, value)
--     -- define your form method here like this
--     return value
-- end

return {
    ThreadCreateForm = ThreadCreateForm, 
    ThreadUpdateForm = ThreadUpdateForm, 
}