-- Generated by file `manage.lua` at 2016-9-10 0:7:16. Inspired by Django. 
-- Modify it as you wish.
local ClassView = require"resty.mvc.view"
local views = require"app.thread.views"
local models = require"app.thread.models"
local forms = require"app.thread.forms"

local Thread = models.Thread

return {
  {'^/thread/create$',              ClassView.CreateView:as_view{model=Thread,form_class=forms.ThreadCreateForm}}, 
  {'^/thread/update/(?<id>\\d+?)$', ClassView.UpdateView:as_view{model=Thread,form_class=forms.ThreadUpdateForm}}, 
  {'^/thread/list/(?<page>\\d+?)$', ClassView.ListView:as_view{model=Thread}}, 
  {'^/thread/(?<id>\\d+?)$',        ClassView.DetailView:as_view{model=Thread}}, 
}