-- Generated by file `manage.lua` at 2016-9-10 0:7:16. Inspired by Django. 
-- Modify it as you wish.
local json = require "cjson.safe"
local query = require"resty.mvc.query".single
local response = require"resty.mvc.response"
local ClassView = require"resty.mvc.view"
local models = require"app.thread.models"
local forms = require"app.thread.forms"

local Thread = models.Thread
local views = {}

-- function views.foobar(request, kwargs)
--     return response.Template("/")
-- end

return views
