    {'/${app_name}/${url_model_name}/create', views.${url_model_name}_create},
    {'/${app_name}/${url_model_name}/update', views.${url_model_name}_update},
    {'/${app_name}/${url_model_name}/list', views.${url_model_name}_list},
    {'/${app_name}/${url_model_name}', views.${url_model_name}_detail},
    {'/${app_name}/${url_model_name}/delete', views.${url_model_name}_delete},