-- Generated by file `manage.lua` at Fri Oct 14 13:25:16 2016.  
local Form = require"resty.mvc.form"
local Widget = require"resty.mvc.widget"
local Field = require"resty.mvc.formfield"
local Validator = require"resty.mvc.validator"
local models = require"apps.moreinfo.models"


local Moreinfo = models.Moreinfo

local MoreinfoCreateForm = Form:class{
    model  = Moreinfo, 
    fields = {
        weight = Field.FloatField{},
        height = Field.FloatField{}
    }, 
}
-- custom form initialization
-- function MoreinfoCreateForm.instance(cls, attrs)
--     local self = Form.instance(cls, attrs)
--     return self
-- end

-- define your form clean method here
-- function MoreinfoCreateForm.clean_fieldname(self, value)
--     return value
-- end


local MoreinfoUpdateForm = Form:class{
    model  = Moreinfo, 
    fields = {
        weight = Field.FloatField{},
        height = Field.FloatField{}
    }, 
}

return {
    MoreinfoCreateForm = MoreinfoCreateForm, 
    MoreinfoUpdateForm = MoreinfoUpdateForm, 
}