-- Generated by file `manage.lua` at Wed Oct 12 10:37:49 2016.  
local Form = require"resty.mvc.form"
local Widget = require"resty.mvc.widget"
local Field = require"resty.mvc.formfield"
local Validator = require"resty.mvc.validator"
local models = require"apps.moreinfo.models"


local Moreinfo = models.Moreinfo

local MoreinfoCreateForm = Form:class{
    model  = Moreinfo, 
    fields = {
        weight = Field.FloatField{},
        height = Field.FloatField{}
    }, 
}
-- function MoreinfoCreateForm.clean_fieldname(self, value)
--     -- define your form method here
--     return value
-- end


local MoreinfoUpdateForm = Form:class{
    model  = Moreinfo, 
    fields = {
        weight = Field.FloatField{},
        height = Field.FloatField{}
    }, 
}
-- function MoreinfoUpdateForm.clean_fieldname(self, value)
--     -- define your form method here
--     return value
-- end

return {
    MoreinfoCreateForm = MoreinfoCreateForm, 
    MoreinfoUpdateForm = MoreinfoUpdateForm, 
}