-- Generated by file `manage.lua` at Fri Oct 14 13:25:16 2016.  
local Model = require"resty.mvc.model"
local Field = require"resty.mvc.modelfield"


local Moreinfo = Model:class{
    table_name = "moreinfo", 
    fields     = {
        weight = Field.FloatField{},
        height = Field.FloatField{}
    }
}
-- define your model methods here
-- function Moreinfo.render(self)
--     return 
-- end

return {
  Moreinfo = Moreinfo, 
}