-- Generated by file `manage.lua` at Wed Oct 12 10:37:49 2016.  
local Model = require"resty.mvc.model"
local Field = require"resty.mvc.modelfield"


local Moreinfo = Model:class{
    table_name = "moreinfo", 
    fields     = {
        weight = Field.FloatField{},
        height = Field.FloatField{}
    }
}
-- function Moreinfo.method(self)
--   -- define your model methods here
-- end

return {
  Moreinfo = Moreinfo, 
}