-- Generated by file `manage.lua` at Fri Oct 14 13:25:16 2016.  
local ClassView = require"resty.mvc.view"
local views = require"apps.moreinfo.views"
local models = require"apps.moreinfo.models"
local forms = require"apps.moreinfo.forms"

local Moreinfo = models.Moreinfo

return {
    {
      '^/moreinfo/create$',              
      ClassView.CreateView:as_view{
        model      = Moreinfo,
        form_class = forms.MoreinfoCreateForm,
      }
    },
  
    {
      '^/moreinfo/update/(?<id>\\d+?)$',              
      ClassView.UpdateView:as_view{
        model      = Moreinfo,
        form_class = forms.MoreinfoUpdateForm,
      }
    },

    {
      '^/moreinfo/list/(?<page>\\d+?)$',              
      ClassView.ListView:as_view{
        model = Moreinfo,
      }
    },

    {
      '^/moreinfo/(?<id>\\d+?)$',              
      ClassView.DetailView:as_view{
        model = Moreinfo,
      }
    },

    {
      '^/moreinfo/delete/(?<id>\\d+?)$',              
      ClassView.DeleteView:as_view{
        model = Moreinfo,
      }
    },
}