-- Generated by file `manage.lua` at Fri Oct 14 13:25:16 2016.  
local json = require "cjson.safe"
local Response = require"resty.mvc.response"
local ClassView = require"resty.mvc.view"
local query = require"resty.mvc.query".single
local models = require"apps.moreinfo.models"
local forms = require"apps.moreinfo.forms"

local Moreinfo = models.Moreinfo

-- function moreinfo_home_view(request)
--     return Response.Template("/")
-- end

return {
    --  moreinfo_home_view = moreinfo_home_view,
}
