-- Generated by file `manage.lua` at Wed Oct 12 10:37:49 2016.  
local json = require "cjson.safe"
local Response = require"resty.mvc.response"
local ClassView = require"resty.mvc.view"
local query = require"resty.mvc.query".single
local models = require"apps.moreinfo.models"
local forms = require"apps.moreinfo.forms"

local Moreinfo = models.Moreinfo
local views = {}

-- function views.method(request)
--     return Response.Template("/")
-- end

return views
