-- Generated by file `manage.lua` at Fri Oct 14 13:25:27 2016.  
local Form = require"resty.mvc.form"
local Widget = require"resty.mvc.widget"
local Field = require"resty.mvc.formfield"
local Validator = require"resty.mvc.validator"
local models = require"apps.detail.models"
local Moreinfo = require"apps.moreinfo.models".Moreinfo

local Detail = models.Detail

local DetailCreateForm = Form:class{
    model  = Detail, 
    fields = {
        sex = Field.BooleanField{},
        age = Field.IntegerField{},
        info = Field.ForeignKey{Moreinfo}
    }, 
}
-- custom form initialization
-- function DetailCreateForm.instance(cls, attrs)
--     local self = Form.instance(cls, attrs)
--     return self
-- end

-- define your form clean method here
-- function DetailCreateForm.clean_fieldname(self, value)
--     return value
-- end


local DetailUpdateForm = Form:class{
    model  = Detail, 
    fields = {
        sex = Field.BooleanField{},
        age = Field.IntegerField{},
        info = Field.ForeignKey{Moreinfo}
    }, 
}

return {
    DetailCreateForm = DetailCreateForm, 
    DetailUpdateForm = DetailUpdateForm, 
}