-- Generated by file `manage.lua` at Wed Oct 12 11:16:56 2016.  
local Model = require"resty.mvc.model"
local Field = require"resty.mvc.modelfield"
local Moreinfo = require"apps.moreinfo.models".Moreinfo

local Detail = Model:class{
    table_name = "detail", 
    fields     = {
        sex = Field.BooleanField{},
        age = Field.IntegerField{},
        info = Field.ForeignKey{Moreinfo}
    }
}
-- function Detail.method(self)
--   -- define your model methods here
-- end

return {
  Detail = Detail, 
}