-- Generated by file `manage.lua` at Fri Oct 14 13:25:27 2016.  
local Model = require"resty.mvc.model"
local Field = require"resty.mvc.modelfield"
local Moreinfo = require"apps.moreinfo.models".Moreinfo

local Detail = Model:class{
    table_name = "detail", 
    fields     = {
        sex = Field.BooleanField{},
        age = Field.IntegerField{},
        info = Field.ForeignKey{Moreinfo}
    }
}
-- define your model methods here
function Detail.render(self)
    return string.format('[sex:%s age:%s]', self.sex, self.age)
end

return {
  Detail = Detail, 
}