-- Generated by file `manage.lua` at Fri Oct 14 13:25:27 2016.  
local ClassView = require"resty.mvc.view"
local views = require"apps.detail.views"
local models = require"apps.detail.models"
local forms = require"apps.detail.forms"

local Detail = models.Detail

return {
    {
      '^/detail/create$',              
      ClassView.CreateView:as_view{
        model      = Detail,
        form_class = forms.DetailCreateForm,
      }
    },
  
    {
      '^/detail/update/(?<id>\\d+?)$',              
      ClassView.UpdateView:as_view{
        model      = Detail,
        form_class = forms.DetailUpdateForm,
      }
    },

    {
      '^/detail/list/(?<page>\\d+?)$',              
      ClassView.ListView:as_view{
        model = Detail,
      }
    },

    {
      '^/detail/(?<id>\\d+?)$',              
      ClassView.DetailView:as_view{
        model = Detail,
      }
    },

    {
      '^/detail/delete/(?<id>\\d+?)$',              
      ClassView.DeleteView:as_view{
        model = Detail,
      }
    },
}