-- Generated by file `manage.lua` at Fri Oct 14 13:25:27 2016.  
local json = require "cjson.safe"
local Response = require"resty.mvc.response"
local ClassView = require"resty.mvc.view"
local query = require"resty.mvc.query".single
local models = require"apps.detail.models"
local forms = require"apps.detail.forms"

local Detail = models.Detail

-- function detail_home_view(request)
--     return Response.Template("/")
-- end

return {
    --  detail_home_view = detail_home_view,
}
